### ISSUE TITLE
Failed: Your \"manala_php_version\" is not compatible with your release

### ISSUE THREAD

**Issue by schneebonus** [systemli/ansible-role-userli#1]
I tried to use the ansible role as described here:
https://systemli.github.io/userli/getting-started/
But there seems to be a problem with my manala_php version. 

### Host OS:
Debian 10
ansible 2.8.4
molecule 2.22
manala_php_version ? (how to check this?)

### Error Message:

    [ ... ]
    TASK [manala.apt : packages > Packages present] ********************************
    ok: [localhost]
    
    TASK [manala.apt : packages > Packages absent] *********************************
    ok: [localhost]
    
    TASK [manala.php : requirements > Version] *************************************
    skipping: [localhost]

    TASK [manala.php : requirements > Version release] *****************************
    fatal: [localhost]: FAILED! => {"changed": false, "msg": "Your \"manala_php_version\" is not compatible with your release"}    

    PLAY RECAP *********************************************************************
    localhost                  : ok=29   changed=0    unreachable=0    failed=1    skipped=22   rescued=0    ignored=0

**Comment by t2d** [comment]
Thank you for your interest in userli and trying it out. Sadly, Buster is not yet supported by manala (https://github.com/manala/ansible-roles/issues/357). I will see, what we can do about this.

**Comment by schneebonus** [comment]
Thanks for the reply and all the work.

I'll have a try with Stretch.

**Comment by t2d** [comment]
I changed some dependencies so everything should be working on Buster now. Let me know if you still have any problem.
